services:
  - type: web
    name: lomy-forex-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js

    envVars:
      - key: NODE_VERSION
        value: 20

      - key: TELEGRAM_BOT_TOKEN
        sync: false

      - key: TWELVE_DATA_API_KEY
        sync: false

      - key: MONGODB_URI
        sync: false

      - key: PORT
        value: 10000
